version: '3'
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=todogo
      - POSTGRES_USER=todo_admin
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  todo-auth:
    build: .
    container_name: todo-auth-container
    ports:
      - "8080:8080"  # Map host port to container port
    depends_on:
      - postgres

volumes:
  postgres: 